language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements-devel.txt
  - pip install coveralls
script:
  - python setup.py develop
  - py.test --cov=helloworld tests/
after_success:
  - coveralls
