apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld
    version: v1
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: canonicalols/helloworld:latest
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /_status/ping
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /users
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
    version: v1
  name: helloworld
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  type: LoadBalancer
